// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma migrations need a direct (non-PgBouncer) connection.
    // Falls back to DATABASE_URL when DIRECT_URL is not set (e.g. Neon).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
